codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
    patch:
      default:
        target: 100%

ignore:
  - "tests/"
  - "**/*test*.rs"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default

# Exclude specific patterns from coverage
# coverage:off and coverage:on comments are recognized by CodeCov
